project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-3FN26ZGN6Q"
  title: "Asquirous"
  favicon: favicon-32x32_vapor2.png
  navbar:
    left:
      - text: Blog
        href: blog.qmd
      - text: Bits
        href: bits.qmd
    right:
      - icon: github
        href: https://github.com/SuchitG04/
      - icon: twitter-x
        href: https://twitter.com/asquirous/
  drafts:
    - posts/backprop/draft.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
