---
title: "Resource preemption, and laser focus."
toc: true
date: "2024-11-20"
author: "Suchit G"
description: "I can multi-task so well 🤡."
---


Resource preemption is an important concept in OS. No, I'm not here to lecture you about it.

To put it simply, the processor pauses the current process and attends to some other process, ideally remembering to come back to the original process.

It is a nifty algorithm. But what about task preemption in humans?

Imagine I'm working hard on a problem — programming, math or anything else.
I remember another task that I had to do. Maybe it's more important, maybe it isn't – we suck at judging that. I switch tasks, preempting the original one.

Now, the probability of me returning promptly to the original task is lower than I'd like it.
Often, I detour through some other task. In other words, our ability to hold the state of the preempted process is remarkably poor.

This hampers my productivity quite a lot.
In fact, a lot of distractions, be it dopamine inducing or any other _actual_ tasks, neatly fit into this paradigm.

This highlights the need for **laser focus**. If you are to complete any given task in optimal time _and not_ half-ass it, "laser focus" is essential.

'tis a fancy term indeed, but by laser focus I mean being focused on a single goal, task, objective, etc.
Maybe there are different ways of thinking about focus in different contexts, I don't know. I'm yet to figure it out.